
// Fix: Removed circular dependency and defined the GeneratedContent type.
// This interface defines the structure of the content generated by the Gemini API.
export interface GeneratedContent {
  script: string;
  titles: string[];
  tags: string[];
  description: string;
  thumbnailPrompts: string[];
}

export interface UserInput {
  projectName: string;
  theme: string;
  tone: string;
  audience: string;
  creativeIdea: string;
  titleIdeas: string;
  descriptionIdeas: string;
  thumbnailIdeas: string;
}

export interface Conversation {
  id: string;
  title: string;
  timestamp: number;
  input: UserInput;
  content: GeneratedContent;
}
